<template>
  <div class="flex flex-col items-center">
    <!-- Menu movil -->
    <div class="self-end pr-12">
      <svg
        class="fixed top-0 h-6 w-6 mt-2 fill-current sm:hidden text-an-cielo cursor-pointer"
        :class="{ hidden: toggleButton }"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        @click="toggleMenu"
      >
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
      </svg>
    </div>
    <div
      class="fixed top-0 scale-in-top flex flex-col w-full h-full sm:hidden"
      :class="{ hidden: hideMobileMenu }"
    >
      <img src="@/assets/img/marble-background.jpg" class="w-full h-full" />
      <!-- SVG para cerrar -->
      <div class="self-end pr-12">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          class="fixed top-0 h-6 w-6 mt-2 sm:hidden text-an-cielo cursor-pointer"
          :class="{ hidden: !toggleButton }"
          @click="toggleMenu"
        >
          <path
            d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z"
          />
        </svg>
      </div>
      <!-- Contiene opciones de menu -->
      <div
        class="flex flex-col font-eras absolute pt-12 w-full text-2xl text-center"
        style="top: 50%; left: 50%; transform: translate(-50%, -50%);"
      >
        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#invitaciones-personalizadas',
            }"
            class="mb-6 px-4"
            >Invitaciones personalizadas</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#nuestros-trabajos',
            }"
            class="mb-6 px-4"
            >Nuestros trabajos</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#sobre-artenupcia',
            }"
            class="mb-6 px-4"
            >Sobre Artenupcia</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#necesitas-inspiracion',
            }"
            class="mb-6 px-4"
            >Inspiración</nuxt-link
          >
        </div>
        <div @click="toggleMenu" class="mb-10 text-gray-700 font-extrabold">
          <nuxt-link to="/contacto" class="mb-6 px-4"
            >Contacto</nuxt-link
          >
        </div>
      </div>
    </div>
    <!--Menu no-movil -->
    <nuxt-link to="/">
      <!-- logo Artenupcia -->
      <img
        src="../assets/img/logo-artenupcia-recortado.png"
        class="w-72 h-48"
      />
    </nuxt-link>
    <h1 class="font-free text-4xl">
      Tu historia, tu invitación
    </h1>

    <div
      class="hidden sm:block sm:w-full sm:px-72"
    >
      <div class="border-t border-an-marron mb-2"></div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      hideMobileMenu: true,
      toggleButton: false,
    };
  },
  methods: {
    toggleMenu() {
      this.hideMobileMenu = !this.hideMobileMenu;
      this.$emit("toggleMenu");
      this.toggleButton = !this.toggleButton;
    },
  },
};
</script>

<style scoped>
.font-free {
  font-family: "Freestyle";
}

.font-eras {
  font-family: "Eraslight";
}

.scale-in-top {
  -webkit-animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-5 19:35:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
}
@keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
}
</style>
