<!-- Contiene logo, elementos del menu solo para movil -->
<template>
  <div
    class="flex flex-col items-center font-semibold text-gray-700 font-znikomit"
  >
    <!-- Menu movil -->
    <div class="self-end pr-12">
      <svg
        class="fixed top-0 w-6 h-6 mt-2 cursor-pointer fill-current sm:hidden text-an-cielo"
        :class="{ hidden: toggleButton }"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        @click="toggleMenu"
      >
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
      </svg>
    </div>
    <div
      class="fixed top-0 flex flex-col w-full h-full scale-in-top sm:hidden"
      :class="{ hidden: hideMobileMenu }"
    >
      <img src="@/assets/img/marble-background.jpg" class="w-full h-full" />
      <!-- SVG para cerrar -->
      <div class="self-end pr-12">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          class="fixed top-0 w-6 h-6 mt-2 cursor-pointer sm:hidden text-an-cielo"
          :class="{ hidden: !toggleButton }"
          @click="toggleMenu"
        >
          <path
            d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z"
          />
        </svg>
      </div>
      <!-- Contiene opciones de menu -->
      <div
        class="absolute flex flex-col w-full pt-12 text-2xl text-center"
        style="top: 50%; left: 50%; transform: translate(-50%, -50%);"
      >
        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#invitaciones-personalizadas',
            }"
            class="px-4 mb-6"
            >Invitaciones personalizadas</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#nuestros-trabajos',
            }"
            class="px-4 mb-6"
            >Nuestros trabajos</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#sobre-artenupcia',
            }"
            class="px-4 mb-6"
            >Sobre Artenupcia</nuxt-link
          >
        </div>

        <div @click="toggleMenu" class="mb-10">
          <nuxt-link
            :to="{
              path: '/',
              hash: '#necesitas-inspiracion',
            }"
            class="px-4 mb-6"
            >Inspiración</nuxt-link
          >
        </div>
        <div @click="toggleMenu" class="mb-10 font-extrabold text-gray-700">
          <nuxt-link to="/contacto" class="mb-6 shadow-text"
            >Contacto</nuxt-link
          >
        </div>
      </div>
    </div>
    <!-- Logo que redirige a la home -->
    <nuxt-link to="/">
      <!-- logo Artenupcia -->
      <img
        src="../assets/img/logo-artenupcia-recortado.png"
        class="h-48 w-72"
      />
    </nuxt-link>
    <!-- Heading text -->
    <h1 class="text-4xl font-medium text-center font-free">
      Invitaciones de boda para el recuerdo
    </h1>

    <div class="hidden sm:block sm:w-full sm:px-72">
      <div class="mb-2 border-t border-an-marron"></div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      hideMobileMenu: true, // controla la visibilidad de los elementos en movil
      toggleButton: false, // para togglear la variable hideMobileMenu
    }
  },
  methods: {
    /** Controla la visibilidad de los elementos del menu movil */
    toggleMenu() {
      this.hideMobileMenu = !this.hideMobileMenu
      this.$emit('toggleMenu')
      this.toggleButton = !this.toggleButton
    },
  },
}
</script>

<style scoped>
.shadow-text {
  box-shadow: inset 0 -0.375em 0 0 rgba(214, 231, 238, 0.8);
}

.font-free {
  font-family: 'Freestyle';
}

.font-eras {
  font-family: 'Eraslight';
}

.font-inkfree {
  font-family: 'Inkfree';
}

.font-znikomit {
  font-family: 'Znikomit';
}

.font-gravity-l {
  font-family: 'GravityLight';
}

.scale-in-top {
  -webkit-animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-5 19:35:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
}
@keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    opacity: 1;
  }
}
</style>
