<!-- Portada Hero para la Home / Contendra un video -->
<template>
  <div class="flex sm:mb-4">
    <div class="relative w-full opacity-75">
      <video
        autoplay
        muted
        loop
        class="content-center object-cover min-w-full h-96 sm:h-136"
      >
        <source
          src="https://artenupcia-files.s3.eu-west-3.amazonaws.com/video1-an-2.mp4"
          type="video/mp4"
        />
      </video>
      <!-- Call to action -->
      <div class="absolute px-2 py-4 btn-style">
        <div class="p-1">
          <button
            class="w-64 px-5 py-3 text-lg font-bold tracking-wide text-gray-700 transition duration-150 ease-in-out bg-opacity-75 border border-transparent rounded-md opacity-75 heartbeat bg-an-salmon hover:border-4 hover:border-white focus:outline-none"
            @click.prevent="$router.push('/contacto')"
          >
            ¡Cuéntanos tu idea!
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style scoped>
.heartbeat {
  -webkit-animation: heartbeat 5s ease-in-out infinite both;
  animation: heartbeat 5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-5 19:31:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}

@media only screen and (min-device-width: 320px) and (max-device-width: 480px) {
  .btn-style {
    bottom: 20px;
    right: 5%;
  }
}

/* Desktops and laptops ----------- */
@media only screen and (min-width: 1224px) {
  .btn-style {
    bottom: 100px;
    right: 5%;
  }
}

/* iPads (portrait and landscape) ----------- */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
  .btn-style {
    bottom: 50px;
    right: 5%;
  }
}

.btn-style {
  bottom: 20px;
  right: 5%;
}
</style>
