<!-- Portada Hero para la Home / Contendra un video -->
<template>
  <div class="flex sm:mb-4">
    <div class="w-full relative opacity-75">
      <video
        autoplay
        muted
        loop
        class="min-w-full object-cover content-center h-96 sm:h-136"
      >
        <source
          src="https://firebasestorage.googleapis.com/v0/b/artenupcia.appspot.com/o/flamelink%2Fmedia%2Fvideo1-an-2.mp4?alt=media&token=99b420e2-9020-4903-ae1e-a7bd926d8a0e"
          type="video/mp4"
        />
      </video>
      <!-- Call to action -->
      <div class="absolute px-2 py-4 btn-style">
        <div class="p-1">
          <button
            class="heartbeat w-64 px-5 py-3 text-lg text-white bg-opacity-75 font-extrabold rounded-md bg-an-salmon border border-transparent hover:border-4 hover:border-white focus:outline-none transition duration-150 ease-in-out opacity-75"
            @click.prevent="$router.push('/contacto')"
          >
            ¡Cuéntanos tu idea!
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style scoped>
.heartbeat {
  -webkit-animation: heartbeat 5s ease-in-out infinite both;
  animation: heartbeat 5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-5 19:31:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
    transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
    transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
    transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}

@media only screen and (min-device-width: 320px) and (max-device-width: 480px) {
  .btn-style {
    bottom: 20px;
    right: 5%;
  }
}

/* Desktops and laptops ----------- */
@media only screen and (min-width: 1224px) {
  .btn-style {
    bottom: 100px;
    right: 5%;
  }
}

/* iPads (portrait and landscape) ----------- */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
  .btn-style {
    bottom: 50px;
    right: 5%;
  }
}
</style>
